# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripci\xf2n')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('nacimiento', models.DateField(blank=True)),
                ('tipo_documento', models.IntegerField(choices=[(1, 'C\xe9dula de Ciudadan\xeda'), (2, 'Tarjeta de Identidad'), (3, 'Tarjeta Pasaporte'), (4, 'C\xe9dula de Extranjer\xeda'), (5, 'Pasaporte')], verbose_name='Tipo de documento')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Numero de identificac\xecon')),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managmen.Ciudad')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripci\xf2n')),
                ('precio', models.FloatField(default=0)),
                ('duracion', models.FloatField(verbose_name='Duracion en meses')),
                ('fecha', models.DateField(blank=True, verbose_name='Fecha de realizacion')),
                ('inicio', models.TimeField(blank=True, verbose_name='Hora de inicio')),
                ('fin', models.TimeField(blank=True, verbose_name='Hora de fin')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managmen.Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripci\xf2n')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripci\xf2n')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripci\xf2n')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managmen.Lugar'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managmen.Ponente'),
        ),
    ]
