# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmen', '0005_auto_20180811_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenciudad',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
