# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmen', '0007_auto_20180811_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugar/'),
        ),
    ]
