# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managmen', '0008_auto_20180811_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugar/'),
        ),
    ]
